config/routes.rb
Greatday::Application.routes.draw do
  devise_for :users, :path=>"auth"
  resources(:users, :only=>[:show])do
	resources :photos, :only=>[:index, :show, :new, :create] do
	  post 'upload', :on=>:collection
	end
  end

  get "static/index"
  root :to => "static#index"

end

app/models/photo.rb
class Photo < ActiveRecord::Base
	attr_accessible :image, :description
	has_attached_file :image, :styles=>{:medium => "300x300>", :thumb=>"100x100>"}
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username
  
  validates_presence_of :username
  validates_uniqueness_of :username

  has_many :photos

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
	def upload
		File.open(upload_path, 'w')do |f|
		 f.write request.raw_post
		end
		render :text =>"ok"
	end
	
	def create
		@photo = Photo.new params[:photo]
		@photo.user = current_user
		@photo.image = File.new(upload_path)
		@photo.save
		render :show
	end
	
	def show
		#@photo = Photo.find params[:id]
		@photos= Photo.find params[:user_id]
		@user = current_user
		reder :index
		respond_to do |format|
    		 format.html # show.html.erb
		 format.xml  { render :xml => @post }
		end
	end

	def index
		#@photos = Photo.all
		@user = current_user
		@photos = Photo.find params[:user_id]
		respond_to do |format|
   		 format.html # index.html.erb
		 format.xml  { render :xml => @posts }
  		end
	end

	def new
		@photo = Photo.new
		@user = current_user
		respond_to do |format|
			format.html # new.html.erb
			format.xml  { render :xml => @photo }
		end

	end	

	private
	def upload_path
		file_name = session[:session_id].to_s + '.jpg'
		File.join(::Rails.root.to_s, 'public', 'uploads', file_name)
	end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 def create
	@user = User.find params[:id]
	@photo = @user.photos  
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
 
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= javascript_include_tag 'webcam'%>
  <%= csrf_meta_tag %>
</head>
<body>
	<header>
	<h1 style=text-align:center><%=link_to "Greatday", root_path%></h1>
	<nav>
		<div style = "position:absolute;left:875px;text-decoration:underline;font-size:18px">
	   <%unless user_signed_in?%>
                
		<%=link_to "Login", new_user_session_path%>
		<%=link_to "Register", new_user_registration_path%>
	   <%else%>
		<%=link_to "Take new photo", new_user_photo_path(current_user)%>
		<%=link_to "See all photos", user_photos_path(current_user)%>
		<%=current_user.username%>
		<%=link_to "Logout", destroy_user_session_path%>
	   <%end%>
		</div>
	</nav>
	</header>
	<p class="notice"><%=flash[:notice]%></p>
	<p class="error"><%=flash[:error]%></p>
	<%= yield %>
	<footer><b> ¡Greatday 2010! Una aplicación super divertida<b/></footer>
        <img src = "http://smiley.cafeswa.be/wp-content/2008/05/smiley-face-have-a-great-day.jpg" alt = "happy face "/>
</body>
</html>

app/views/photos/index.html.erb
<h1>All Photos</h1>

<ul>
	<%[current_user, @photos].each do |photo| %>
	<ol><%= link_to image_tag(@photos.image.url(:thumb)),photo=>:user_id%>
		<p><%=@photos.description%></p>
	</ol>
	<% end %>
</ul>
<p>
	<%= link_to "Take a new picture", new_user_photo_path(current_user) %>
</p>

app/views/photos/new.html.erb
<h1>New Photo</h1>

<div id="webcam"></div>
<script type="text/javascript">
  webcam.set_swf_url('/webcam.swf');
  webcam.set_api_url('<%=upload_user_photos_path(current_user)%>');
  webcam.set_quality(90);
  webcam.set_shutter_sound(true, '/shutter.mp3');
  $('webcam').innerHTML = webcam.get_html(640,480);
  webcam.set_hook('onComplete', 'upload complete');

function upload_complete(msg){
        if(msg == 'ok'){
                $('new_user_photo').show();
                $('user_photo_description').focus();
        }else{
                alert('And error occured');
                webcam.reset();
        }
}

</script>

<input type="button" value="Take picture"
		 onclick = "webcam.snap();"/>

<%=form_for [current_user,@photo], :html =>{:style => ":display: none;"} do |f|%>
 <p>
   <%=f.label :description%><br />
   <%=f.text_field :description%>
 </p>
 <p>
   <%=f.submit "Save the photo"%>
   or <%=link_to "Take another", new_user_photo_path(current_user)%>
 </p>
<%end%>

app/views/photos/show.html.erb
<h1>My Photo</h1>
<p><%= image_tag(@photo.image.url(:medium))%></p>
<p>
 <strong>Description:</strong><br />
 <p><%= @photo.description %></p>
</p>
<p>
 <%= link_to "Take a new picture", new_user_photo_path(current_user) %>| 
 <%= link_to "See all pictures", user_photos_path(current_user) %>
</p>